# Generated by Django 2.0 on 2018-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fulldesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adhar', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=2)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('o', 'other')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=50)),
                ('adhar', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('confirmpassword', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('o', 'other')], max_length=50, null=True)),
            ],
        ),
    ]
